<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1282" started-at="2018-06-14T19:27:55Z" finished-at="2018-06-14T19:27:56Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1282" started-at="2018-06-14T19:27:55Z" finished-at="2018-06-14T19:27:56Z">
      <class name="executionEngine.RunTestNG1">
        <test-method status="PASS" signature="setUp()[pri:0, instance:executionEngine.RunTestNG1@4667ae56]" name="setUp" is-config="true" duration-ms="5" started-at="2018-06-15T00:57:55Z" finished-at="2018-06-15T00:57:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="Testcase1()[pri:0, instance:executionEngine.RunTestNG1@4667ae56]" name="Testcase1" duration-ms="1257" started-at="2018-06-15T00:57:55Z" finished-at="2018-06-15T00:57:56Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at support.Keyword.getscreenshot(Keyword.java:887)
	at support.ExecuteTestcase.execute_Actions(ExecuteTestcase.java:104)
	at support.ExecuteTestcase.execute_TestCase(ExecuteTestcase.java:67)
	at executionEngine.RunTestNG1.Testcase1(RunTestNG1.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testcase1 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:executionEngine.RunTestNG1@4667ae56]" name="tearDown" is-config="true" duration-ms="0" started-at="2018-06-15T00:57:56Z" finished-at="2018-06-15T00:57:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- executionEngine.RunTestNG1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
